---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: bosh-softlayer-tools
- name: cf-artifacts-comm

run:
  path: bosh-softlayer-tools/ci/deploy_cf_by_cpi_ng/tasks/verify-cf.sh

outputs:
- name: cf-artifacts
  path: cf-artifacts

params:
  SYSTEM_DOMAIN: 			  replace-me
