---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: zhanggongsw/bosh

inputs:
  - name: bosh-softlayer-tools-master
  - name: bosh-softlayer-tools
  - name: version
  - name: stemcell-cmds
outputs:
  - name: stemcell-image

run:
  path: bosh-softlayer-tools-master/ci/bluemix/tasks/import-stemcell.sh

params:
  IAAS:            bluemix
  HYPERVISOR:      xen
  OS_NAME:         ubuntu
  OS_VERSION:      trusty
  SL_USERNAME:     replace-me
  SL_API_KEY:      replace-me
  SWIFT_USERNAME:  replace-me
  SWIFT_API_KEY:   replace-me
  SWIFT_CLUSTER:   replace-me
  SWIFT_CONTAINER: replace-me