---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: docker:///zhanggongsw/bosh

inputs:
  - name: bosh-softlayer-tools
  - name: stemcell-version
  - name: candidate-stemcell-ubuntu-trusty

run:
  path: bosh-softlayer-tools/ci/tasks/convert-stemcell
