---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: bosh-softlayer-tools
- name: director-artifacts

run:
  path: bosh-softlayer-tools/ci/deploy_cf_by_cpi_ng/tasks/teardown.sh

params:
  DEPLOYMENT_BlUEMIX_NAME:   ""
  DEPLOYMENT_COMMUNITY_NAME: ""
