---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: director-artifacts
- name: bosh-softlayer-tools
- name: run-utils
- name: cf-artifacts

run:
  path: bosh-softlayer-tools/ci/deploy_cf_by_cpi_ng/tasks/update-dns-bluemix.sh

