---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: bosh-softlayer-tools
- name: director-artifacts
- name: cf-app

run:
  path: bosh-softlayer-tools/ci/deploy_cf_by_cpi_ng/tasks/verify-cf-bluemix.sh

params:
  CF_USERNAME: 		replace-me
  CF_PASSWORD: 		replace-me
  APP_API: 			  replace-me