---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: posijon/slci

inputs:
  - name: bosh-softlayer-tools
  - name: stemcell
  - name: version

run:
  path: bosh-softlayer-tools/ci/tasks/convert-stemcell
