---
groups:
  - name: all
    jobs:
      - build-stemcell
      - publish-stemcells
      - test-stemcells
      - build-softlayer-xen-ubuntu-trusty
      - convert-stemcell
      - import-stemcell
      - create-light-stemcell
      - bats-ubuntu
  - name: softlayer
    jobs:
      - build-softlayer-xen-ubuntu-trusty
  - name: ubuntu
    jobs:
      - build-softlayer-xen-ubuntu-trusty
  - name: bats
    jobs:
      - bats-ubuntu

shared:
  - &prepare-director
    task: prepare-director
    file: pipelines/softlayer/tasks/prepare-director.yml
    params: &prepare-director-params
      BOSH_USER:                            {{stemcell-test-director-username}}
      BOSH_PASSWORD:                        {{stemcell-test-director-password}}
      SL_USERNAME:                          {{softlayer_username}}
      SL_API_KEY:                           {{softlayer_api_key}}
      SL_DATACENTER:                        {{softlayer_datacenter}}
      SL_VLAN_PUBLIC:                       {{softlayer_vlan_public}}
      SL_VLAN_PRIVATE:                      {{softlayer_vlan_private}}
      SL_VM_NAME_PREFIX:                    {{softlayer_director_name_prefix}}
      SL_VM_DOMAIN:                         {{softlayer_director_host_domain}}

  - &deploy-director
    task: deploy-director
    file: pipelines/shared/tasks/deploy-director.yml
    params: *prepare-director-params

  - &prepare-bats
    task: prepare-bats
    file: pipelines/softlayer/tasks/prepare-bats.yml
    params: &prepare-bats-params
      BAT_VCAP_PASSWORD:      {{bat-vcap-password}}
      BOSH_USER:              {{stemcell-test-director-username}}
      BOSH_PASSWORD:          {{stemcell-test-director-password}}
      BAT_SECOND_STATIC_IP:       {{bat_second_static_ip}}
      SL_DATACENTER:              {{softlayer_datacenter}}
      SL_VLAN_PUBLIC:             {{softlayer_vlan_public}}
      SL_VLAN_PRIVATE:            {{softlayer_vlan_private}}
      SL_VM_NAME_PREFIX:          {{softlayer_bats_name_prefix}}
      SL_VM_DOMAIN: {{softlayer_director_host_domain}}

  - &run-bats
    task: run-bats
    file: pipelines/shared/tasks/run-bats.yml

  - &teardown
    task: teardown
    file: pipelines/shared/tasks/teardown.yml
    params:
      DEPLOYMENT_NAME: certification

jobs:
  - name: build-stemcell
    serial: true
    plan:
      - get: published-stemcell
      - get: bosh-softlayer-tools
      - task: make-version
        file: bosh-softlayer-tools/ci/tasks/make-stemcell-version.yml
      - put: version
        params:
          file: version/number

  - name: test-stemcells
    serial: true
    plan:
      - aggregate:
        - get: version
          trigger: true
          passed:
            - create-light-stemcell
        - get: bosh-src
        - get: bosh-softlayer-tools
        - get: bosh-cli
        - get: syslog-release
        - get: bosh-release
        - get: cpi-release
        - get: light-stemcell
          trigger: true
          passed:
            - create-light-stemcell

      - do:
        - task: deploy-director
          file: bosh-softlayer-tools/ci/pipelines/stemcells/tasks/deploy-director.yml
          input_mapping:
            stemcell: light-stemcell
          params:
            BOSH_DIRECTOR_USERNAME:               {{stemcell-test-director-username}}
            BOSH_DIRECTOR_PASSWORD:               {{stemcell-test-director-password}}
            SL_USERNAME:                          {{softlayer_username}}
            SL_API_KEY:                           {{softlayer_api_key}}
            SL_DATACENTER:                        {{softlayer_datacenter}}
            SL_VLAN_PUBLIC:                       {{softlayer_vlan_public}}
            SL_VLAN_PRIVATE:                      {{softlayer_vlan_private}}
            SL_VM_NAME_PREFIX:                    {{softlayer_director_name_prefix}}
            SL_VM_DOMAIN:                         {{softlayer_director_host_domain}}
        - task: test-stemcell
          file: bosh-src/bosh-stemcell/smoke/test-stemcell.yml
          input_mapping:
            stemcell: light-stemcell
          params:
            BOSH_DIRECTOR_USERNAME:       {{stemcell-test-director-username}}
            BOSH_DIRECTOR_PASSWORD:       {{stemcell-test-director-password}}
            SL_DATACENTER:                        {{softlayer_datacenter}}
            SL_VLAN_PUBLIC:                       {{softlayer_vlan_public}}
            SL_VLAN_PRIVATE:                      {{softlayer_vlan_private}}
            SL_VM_NAME_PREFIX:                    {{softlayer_stemcell_test_prefix}}
            SL_VM_DOMAIN:                         {{softlayer_stemcell_test_domain}}
        ensure:
          do:
          - task: teardown
            file: bosh-softlayer-tools/ci/pipelines/stemcells/tasks/teardown.yml

  - name: publish-stemcells
    serial: true
    plan:
      - aggregate:
        - get: version
          trigger: true
          passed:
            - test-stemcells
            - bats-ubuntu
        - get: bosh-softlayer-tools
      - task: copy-artifacts
        file: bosh-softlayer-tools/ci/pipelines/stemcells/tasks/publish.yml
        params:
          AWS_ACCESS_KEY_ID: {{stemcell_aws_access_key}}
          AWS_SECRET_ACCESS_KEY: {{stemcell_aws_secret_key}}
          CANDIDATE_BUCKET_NAME: {{candidate_bluemix_stemcell_bucket}}
          PUBLISHED_BUCKET_NAME: {{published_bluemix_stemcell_bucket}}
          COPY_KEYS: |
            light-bosh-stemcell-%s-softlayer-xen-ubuntu-trusty-go_agent.tgz
  #
  # SoftLayer
  #

  - name: build-softlayer-xen-ubuntu-trusty
    plan:
      - aggregate:
          - get: version
            trigger: true
            passed: [build-stemcell]
          - get: bosh-src
          - get: bosh-softlayer-tools
      - task: create-stemcell
        file: bosh-softlayer-tools/ci/pipelines/stemcells/tasks/build.yml
        privileged: true
        params:
          IAAS:         softlayer
          HYPERVISOR:   xen
          OS_NAME:      ubuntu
          OS_VERSION:   trusty
      - aggregate:
        - put: softlayer-xen-ubuntu-trusty
          params:
            file: stemcell/*.tgz

  - name: convert-stemcell
    plan:
      - get: version
        trigger: true
        passed: [build-softlayer-xen-ubuntu-trusty]
      - get: bosh-softlayer-tools
      - get: softlayer-xen-ubuntu-trusty
        passed: [build-softlayer-xen-ubuntu-trusty]
        trigger: true
      - task: convert-stemcell
        file: bosh-softlayer-tools/ci/tasks/convert-stemcell.yml
        input_mapping:
          stemcell: softlayer-xen-ubuntu-trusty
        params:
          SWIFT_USERNAME: {{SWIFT_USERNAME}}
          SWIFT_API_KEY: {{softlayer_api_key}}
          SWIFT_CLUSTER: {{SWIFT_CLUSTER}}
          SWIFT_CONTAINER: {{SWIFT_CONTAINER}}
          IAAS:         softlayer
          HYPERVISOR:   xen
          OS_NAME:      ubuntu
          OS_VERSION:   trusty

  - name: import-stemcell
    plan:
      - get: version
        trigger: true
        passed: [convert-stemcell]
      - get: bosh-softlayer-tools
      - task: import-stemcell-image
        file: bosh-softlayer-tools/ci/tasks/import-stemcell.yml
        params:
          SL_USERNAME: {{softlayer_username}}
          SL_API_KEY: {{softlayer_api_key}}
          SWIFT_USERNAME: {{SWIFT_USERNAME}}
          SWIFT_CLUSTER: {{SWIFT_CLUSTER}}
          SWIFT_CONTAINER: {{SWIFT_CONTAINER}}
          IAAS:         softlayer
          HYPERVISOR:   xen
          OS_NAME:      ubuntu
          OS_VERSION:   trusty
      - put: stemcell-info
        params: {file: stemcell-image/stemcell-info.json}

  - name: create-light-stemcell
    plan:
      - aggregate:
          - get: bosh-softlayer-tools
          - get: version
            trigger: true
            passed: [import-stemcell]
          - get: stemcell-info
            passed: [import-stemcell]
            trigger: true
      - task: create-light-stemcell
        file: bosh-softlayer-tools/ci/tasks/create-light-stemcell.yml
        params:
          IAAS:         softlayer
          HYPERVISOR:   xen
          OS_NAME:      ubuntu
          OS_VERSION:   trusty
          SL_USERNAME: {{softlayer_username}}
          SL_API_KEY:  {{softlayer_api_key}}
          BOSHIO_TOKEN: {{boshio_checksum_token}}
      - put: light-stemcell
        params: {file: light-stemcell/*.tgz}

  - name: bats-ubuntu
    serial: false
    plan:
    - do:
      - aggregate:
        - get: bosh-release
        - get: cpi-release
        - get: stemcell
          trigger: true
          resource: light-stemcell
          passed:
            - create-light-stemcell
        - get: pipelines
        - get: bosh-cli
        - get: bats
        - get: version
          trigger: true
          passed:
            - create-light-stemcell

      - <<: *prepare-director

      - do:
        - <<: *deploy-director

        - <<: *prepare-bats
          params:
            <<: *prepare-bats-params
            STEMCELL_NAME: bosh-softlayer-xen-ubuntu-trusty-go_agent

        - <<: *run-bats
        ensure:
          do:
          - <<: *teardown

resources:
  - name: published-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      tarball: false

  - name: bosh-src
    type: git
    source:
      uri: {{bosh_src_url}}
      branch: {{bluemix-stemcell-branch}}

  - name: version
    type: semver
    source:
      driver: s3
      key: bosh-stemcell/version-3312.x
      bucket: {{candidate_stemcell_bucket}}
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}

  - name: syslog-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/syslog-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-softlayer-cpi-release

  #
  # SoftLayer
  #

  - name: softlayer-xen-ubuntu-trusty
    type: s3
    source:
      regexp: bosh-stemcell-(.*)-softlayer-esxi-ubuntu-trusty-go_agent.tgz
      bucket: {{candidate_bluemix_stemcell_bucket}}
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}

  - name: stemcell-info
    type: s3
    source:
      bucket: {{candidate_bluemix_stemcell_bucket}}
      versioned_file: stemcell-info.json
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}

  - name: bosh-softlayer-tools
    type: git
    source:
      uri: https://github.com/mattcui/bosh-softlayer-tools
      branch: container_based_stemcell_pipeline

  - name: light-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-(.*)-softlayer-(.*).tgz
      bucket: {{candidate_bluemix_stemcell_bucket}}
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}

  #
  # BATs
  #

  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1

  - name: pipelines
    type: git
    source:
      uri: https://github.com/jianqiu/bosh-cpi-certification
      branch: master

  - name: bats
    type: git
    source:
      uri: https://github.com/mattcui/bosh-acceptance-tests
      branch: master
