---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: director-artifacts
- name: bosh-softlayer-tools
- name: cf-deployment

run:
  path: bosh-softlayer-tools/ci/softlayer_ng/tasks/deploy-cf.sh

outputs:
- name: cf-artifacts
- name: deploy-status

params:
  DEPLOYMENT_NAME:                       ""
  SL_DATACENTER:                         ""
  SL_VLAN_PUBLIC:                        ""
  SL_VLAN_PRIVATE:                       ""
  DEPLOY_NAME:                           ""
  CF_PREFIX:                             ""
