---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: bosh-softlayer-tools
- name: cf-artifacts-comm
  path: cf-artifacts

run:
  path: bosh-softlayer-tools/ci/softlayer_ng/tasks/update-dns.sh

params:
  SYSTEM_DOMAIN:                         ""
