resources:
- name: director-artifacts
  type: s3
  source:
    bucket: bosh-softlayer-create-cf-env
    versioned_file: director_artifacts.tgz
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
- name: cf-artifacts
  type: s3
  source:
    bucket: bosh-softlayer-create-cf-env
    versioned_file: cf_artifacts.tgz
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}    
- name: bosh-cli-v2
  type: s3
  source:
    bucket: bosh-softlayer-artifacts
    regexp: bosh-cli-([0-9.]+)-softlayer-linux-amd64
- name: bosh-softlayer-tools-master
  type: git
  source:
    branch: master
    uri: https://github.com/bluebosh/bosh-softlayer-tools    
    private_key: {{github_private_key}}
- name: bosh-deployment-new-softlayer-cpi
  type: git
  source:
    uri: https://github.com/bluebosh/bosh-deployment
    branch: new_softlayer_cpi
- name: cf-deployment-new-softlayer-cpi
  type: git
  source:
    uri: https://github.com/bluebosh/cf-deployment
    branch: new_softlayer_cpi

jobs:
- name: deploy-director-base
  serial: true
  plan:
  - aggregate:
    - get: bosh-cli-v2
      resource: bosh-cli-v2
    - get: bosh-softlayer-tools
      resource: bosh-softlayer-tools-master
    - get: bosh-deployment
      resource: bosh-deployment-new-softlayer-cpi
  - task: deploy
    file: bosh-softlayer-tools/ci/softlayer_ng/tasks/deploy-director.yml
    params:
      INFRASTRUCTURE:                      softlayer
      SL_VM_PREFIX:                        {{softlayer-director-name-prefix}}
      SL_VM_DOMAIN:                        {{softlayer-vm-domain}}
      CF_PREFIX:                           {{softlayer-cf-prefix}}
      SL_USERNAME:                         {{softlayer-username}}
      SL_API_KEY:                          {{softlayer-api-key}}
      SL_DATACENTER:                       {{softlayer-datacenter}}
      SL_VLAN_PUBLIC:                      {{softlayer-vlan-public}}
      SL_VLAN_PRIVATE:                     {{softlayer-vlan-private}}
  - put: director-artifacts
    params:
      file: deploy-artifacts/director_artifacts.tgz

- name: deploy-cf-base
  plan:
  - aggregate:
    - get: director-artifacts
      resource: director-artifacts
      passed:
      - deploy-director-base
    - get: bosh-softlayer-tools
      resource: bosh-softlayer-tools-master
    - get: cf-deployment
      resource: cf-deployment-new-softlayer-cpi
  - task: deploy-cf
    file: bosh-softlayer-tools/ci/softlayer_ng/tasks/deploy-cf.yml
    params:
      DEPLOYMENT_NAME:                        {{deployment-name}}
      SL_DATACENTER:                          {{softlayer-datacenter}}
      SL_VLAN_PUBLIC:                         {{softlayer-vlan-public}}
      SL_VLAN_PRIVATE:                        {{softlayer-vlan-private}}
      CF_PREFIX:                              {{softlayer-cf-prefix}}
      CF_DOMAIN:                              {{softlayer-cf-domain}}
  - put: cf-artifacts
    params:
      file: cf-artifacts/cf_artifacts.tgz

- name: deploy-cf-base
  plan:
  - aggregate:
    - get: director-artifacts
      resource: director-artifacts
      passed:
      - deploy-director-base
    - get: bosh-softlayer-tools
      resource: bosh-softlayer-tools-master
    - get: cf-artifacts
      resource: cf-artifacts
  - task: update-dns
    file: bosh-softlayer-tools/ci/softlayer_ng/tasks/update-dns.yml
    params:
      VCAP_PASSWORD:                       {{vcap-password}}